//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pritisni Enter).
        /// </summary>
        internal static string _Press_Enter_ {
            get {
                return ResourceManager.GetString("(Press Enter)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pritisni Enter za vise).
        /// </summary>
        internal static string _Press_Enter_for_more_ {
            get {
                return ResourceManager.GetString("(Press Enter for more)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pritisni enter za vise).
        /// </summary>
        internal static string _Press_enter_for_more_info_ {
            get {
                return ResourceManager.GetString("(Press enter for more info)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pritisni Enter da kreiras).
        /// </summary>
        internal static string _Press_Enter_to_create_ {
            get {
                return ResourceManager.GetString("(Press Enter to create)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pritisni enter da ocijenis).
        /// </summary>
        internal static string _Press_Enter_to_rate_ {
            get {
                return ResourceManager.GetString("(Press Enter to rate)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pritisni Enter za pracenje).
        /// </summary>
        internal static string _Press_Enter_to_track_ {
            get {
                return ResourceManager.GetString("(Press Enter to track)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije O Aktivnoj Turi.
        /// </summary>
        internal static string Active_Tour_Information {
            get {
                return ResourceManager.GetString("Active Tour Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivne ture(Ctrl+Tab).
        /// </summary>
        internal static string Active_tours_Ctrl_Tab_ {
            get {
                return ResourceManager.GetString("Active tours(Ctrl+Tab)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj fotografije:.
        /// </summary>
        internal static string Add_photos_ {
            get {
                return ResourceManager.GetString("Add photos:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj informacije o turisti:.
        /// </summary>
        internal static string Add_tourist_information_ {
            get {
                return ResourceManager.GetString("Add tourist information:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godine:.
        /// </summary>
        internal static string Age_ {
            get {
                return ResourceManager.GetString("Age:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisustvo na turi:.
        /// </summary>
        internal static string Attendance_at_the_tour_information_ {
            get {
                return ResourceManager.GetString("Attendance at the tour information:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosjecan broj ljudi u prihvacenim zahtjevima.
        /// </summary>
        internal static string Average_number_of_people_in_accepted_requests_ {
            get {
                return ResourceManager.GetString("Average number of people in accepted requests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkazi.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni temu:.
        /// </summary>
        internal static string Change_apperiance_ {
            get {
                return ResourceManager.GetString("Change apperiance:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni jezik:.
        /// </summary>
        internal static string Change_language_ {
            get {
                return ResourceManager.GetString("Change language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad:.
        /// </summary>
        internal static string City_ {
            get {
                return ResourceManager.GetString("City:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori(Ctrl+C).
        /// </summary>
        internal static string Close_Ctrl_C_ {
            get {
                return ResourceManager.GetString("Close(Ctrl+C)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompleksna tura.
        /// </summary>
        internal static string Complex_tour {
            get {
                return ResourceManager.GetString("Complex tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompleksna tura:.
        /// </summary>
        internal static string Complex_tour_ {
            get {
                return ResourceManager.GetString("Complex tour:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompleksna tura se sastoji od dvije ili vise obicnih tura.
        /// </summary>
        internal static string Complex_tour_is_made_of_two_or_more_ordinary_tours {
            get {
                return ResourceManager.GetString("Complex tour is made of two or more ordinary tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtjev za kompleksnu turu:.
        /// </summary>
        internal static string Complex_tour_request_ {
            get {
                return ResourceManager.GetString("Complex tour request:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtjevi Za Slozene Ture(Ctrl+Tab).
        /// </summary>
        internal static string Complex_Tour_Requests_Ctrl_Tab_ {
            get {
                return ResourceManager.GetString("Complex Tour Requests(Ctrl+Tab)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi zahtjev.
        /// </summary>
        internal static string Confirm_request {
            get {
                return ResourceManager.GetString("Confirm request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi Rezervaciju.
        /// </summary>
        internal static string Confirm_Reservation {
            get {
                return ResourceManager.GetString("Confirm Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drzava:.
        /// </summary>
        internal static string Country_ {
            get {
                return ResourceManager.GetString("Country:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj Zahtjev Za Slozenu Turu.
        /// </summary>
        internal static string Create_Complex_Tour_Request {
            get {
                return ResourceManager.GetString("Create Complex Tour Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj Zahjtev Za Obicnu Turu.
        /// </summary>
        internal static string Create_ordinary_tour_request {
            get {
                return ResourceManager.GetString("Create ordinary tour request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj Zahtjev(F4).
        /// </summary>
        internal static string Create_Request_F4_ {
            get {
                return ResourceManager.GetString("Create Request(F4)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj Zahtjev Za Turu.
        /// </summary>
        internal static string Create_Tour_Request {
            get {
                return ResourceManager.GetString("Create Tour Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutan kapacitet:.
        /// </summary>
        internal static string Current_capacity_ {
            get {
                return ResourceManager.GetString("Current capacity:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum:.
        /// </summary>
        internal static string Date_ {
            get {
                return ResourceManager.GetString("Date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval datuma.
        /// </summary>
        internal static string Date_Interval {
            get {
                return ResourceManager.GetString("Date Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval datuma:.
        /// </summary>
        internal static string Date_interval_ {
            get {
                return ResourceManager.GetString("Date interval:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis:.
        /// </summary>
        internal static string Description_ {
            get {
                return ResourceManager.GetString("Description:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje:.
        /// </summary>
        internal static string Duration_ {
            get {
                return ResourceManager.GetString("Duration:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vazi do:.
        /// </summary>
        internal static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavrsene ture.
        /// </summary>
        internal static string Finished_tours {
            get {
                return ResourceManager.GetString("Finished tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za odredjenu godinu.
        /// </summary>
        internal static string for_a_specific_year {
            get {
                return ResourceManager.GetString("for a specific year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za sve godine.
        /// </summary>
        internal static string for_all_years {
            get {
                return ResourceManager.GetString("for all years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od:.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od:.
        /// </summary>
        internal static string From_ {
            get {
                return ResourceManager.GetString("From:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od datuma:.
        /// </summary>
        internal static string From_date_ {
            get {
                return ResourceManager.GetString("From date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vodic:.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vodicevo znanje:(pritisnite razmak da selektujete ocjenu).
        /// </summary>
        internal static string Guide_knowledge___press_spacebar_to_select_a_grade_ {
            get {
                return ResourceManager.GetString("Guide knowledge: (press spacebar to select a grade)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vodicev jezik: (pritisnite razmak da selektujete ocjenu).
        /// </summary>
        internal static string Guide_language___press_spacebar_to_select_a_grade_ {
            get {
                return ResourceManager.GetString("Guide language: (press spacebar to select a grade)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home(F1).
        /// </summary>
        internal static string Home_F1_ {
            get {
                return ResourceManager.GetString("Home(F1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanduce.
        /// </summary>
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanduce(F7).
        /// </summary>
        internal static string Inbox_F7_ {
            get {
                return ResourceManager.GetString("Inbox(F7)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije:.
        /// </summary>
        internal static string Information_ {
            get {
                return ResourceManager.GetString("Information:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tacka ukljucenja.
        /// </summary>
        internal static string Joining_KeyPoint {
            get {
                return ResourceManager.GetString("Joining KeyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kljucne tacke:.
        /// </summary>
        internal static string KeyPoints_ {
            get {
                return ResourceManager.GetString("KeyPoints:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik:.
        /// </summary>
        internal static string Language_ {
            get {
                return ResourceManager.GetString("Language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostavite komentar:.
        /// </summary>
        internal static string Leave_a_comment_ {
            get {
                return ResourceManager.GetString("Leave a comment:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svijetla.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista turista:.
        /// </summary>
        internal static string List_of_tourists_ {
            get {
                return ResourceManager.GetString("List of tourists:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija:.
        /// </summary>
        internal static string Location_ {
            get {
                return ResourceManager.GetString("Location:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava(F8).
        /// </summary>
        internal static string LogOut_F8_ {
            get {
                return ResourceManager.GetString("LogOut(F8)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi zahtjev.
        /// </summary>
        internal static string Make_request {
            get {
                return ResourceManager.GetString("Make request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi Rezervaciju.
        /// </summary>
        internal static string Make_Reservation {
            get {
                return ResourceManager.GetString("Make Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pravljenje rezervacije za:.
        /// </summary>
        internal static string Making_reservation_for_ {
            get {
                return ResourceManager.GetString("Making reservation for:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalno Turista:.
        /// </summary>
        internal static string Max_Tourists_ {
            get {
                return ResourceManager.GetString("Max Tourists:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poruka:.
        /// </summary>
        internal static string Message_ {
            get {
                return ResourceManager.GetString("Message:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vise informacija.
        /// </summary>
        internal static string More_info {
            get {
                return ResourceManager.GetString("More info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje Aktivne Ture.
        /// </summary>
        internal static string My_active_tours {
            get {
                return ResourceManager.GetString("My active tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje Ture(F2).
        /// </summary>
        internal static string My_Tours_F2_ {
            get {
                return ResourceManager.GetString("My Tours(F2)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje Neaktivne ture.
        /// </summary>
        internal static string My_unactive_tours {
            get {
                return ResourceManager.GetString("My unactive tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        internal static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Jezika.
        /// </summary>
        internal static string Number_of_Languages {
            get {
                return ResourceManager.GetString("Number of Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj lokacija.
        /// </summary>
        internal static string Number_of_Locations {
            get {
                return ResourceManager.GetString("Number of Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj ljudi:.
        /// </summary>
        internal static string Number_of_people {
            get {
                return ResourceManager.GetString("Number of people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broj zahtjeva uzavisnosti od jezika.
        /// </summary>
        internal static string number_of_requests_depending_on_languages {
            get {
                return ResourceManager.GetString("number of requests depending on languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broj zahtjeva uzavisnosti od lokacije.
        /// </summary>
        internal static string number_of_requests_depending_on_locations {
            get {
                return ResourceManager.GetString("number of requests depending on locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obicna tura.
        /// </summary>
        internal static string Ordinary_tour {
            get {
                return ResourceManager.GetString("Ordinary tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtjev za obicnu turu:.
        /// </summary>
        internal static string Ordinary_tour_request_ {
            get {
                return ResourceManager.GetString("Ordinary tour request:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obicni Zahtjevi Za Ture(Ctrl+Tab).
        /// </summary>
        internal static string Ordinary_Tour_Requests_Ctrl_Tab_ {
            get {
                return ResourceManager.GetString("Ordinary Tour Requests(Ctrl+Tab)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika Obicnih Zahtjeva.
        /// </summary>
        internal static string Ordinary_Tour_Requests_Statistics_ {
            get {
                return ResourceManager.GetString("Ordinary Tour Requests Statistics:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika Obicnih Zahtjeva Za Ture(Ctrl+Tab).
        /// </summary>
        internal static string Ordinary_Tour_Requests_Statistics_Ctrl_Tab_ {
            get {
                return ResourceManager.GetString("Ordinary Tour Requests Statistics(Ctrl+Tab)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo Vas, izaberite tip zahtjeva koji zelite da napravite:.
        /// </summary>
        internal static string Please_choose_a_type_of_request_You_want_to_make_ {
            get {
                return ResourceManager.GetString("Please choose a type of request You want to make:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritisnite ovdje da kreirate obicnu turu (dio kompleksne ture).
        /// </summary>
        internal static string Press_here_to_create_ordinary_tour__part_of_complex_tour_ {
            get {
                return ResourceManager.GetString("Press here to create ordinary tour (part of complex tour)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodno izabrana tura je puna. Ovo je lista tura istom lokacijom:.
        /// </summary>
        internal static string Previously_selected_tour_is_full__Here_is_a_list_of_alternarive_tours_with_the_same_location_ {
            get {
                return ResourceManager.GetString("Previously selected tour is full. Here is a list of alternarive tours with the sa" +
                        "me location:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocijeni kategorije na skali od 1 do 5:(navigirajte strelicama).
        /// </summary>
        internal static string Rate_categories_on_scale_from_1_to_5___to_navigate_use_arrows_ {
            get {
                return ResourceManager.GetString("Rate categories on scale from 1 to 5: (to navigate use arrows)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocijeni turu.
        /// </summary>
        internal static string Rate_tour {
            get {
                return ResourceManager.GetString("Rate tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocijeni Turu(F5).
        /// </summary>
        internal static string Rate_Tour_F5_ {
            get {
                return ResourceManager.GetString("Rate Tour(F5)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procitano.
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osvjezi.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        internal static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podesavanja.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz statistike za:.
        /// </summary>
        internal static string Showing_statistics_for_ {
            get {
                return ResourceManager.GetString("Showing statistics for:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime:.
        /// </summary>
        internal static string Surname_ {
            get {
                return ResourceManager.GetString("Surname:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do:.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do datuma:.
        /// </summary>
        internal static string To_date_ {
            get {
                return ResourceManager.GetString("To date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tura.
        /// </summary>
        internal static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji ture:.
        /// </summary>
        internal static string Tour_details_ {
            get {
                return ResourceManager.GetString("Tour details:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zanimljivost ture:(pritisnite razmak da selektujete ocjenu).
        /// </summary>
        internal static string Tour_entertainment___press_spacebar_to_select_a_grade_ {
            get {
                return ResourceManager.GetString("Tour entertainment: (press spacebar to select a grade)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv ture:.
        /// </summary>
        internal static string Tour_name_ {
            get {
                return ResourceManager.GetString("Tour name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtjevi Tura(F3).
        /// </summary>
        internal static string Tour_Requests_F3_ {
            get {
                return ResourceManager.GetString("Tour Requests(F3)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status ture:.
        /// </summary>
        internal static string Tour_status_ {
            get {
                return ResourceManager.GetString("Tour status:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o turistima:.
        /// </summary>
        internal static string Tourist_information_ {
            get {
                return ResourceManager.GetString("Tourist information:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prati turu.
        /// </summary>
        internal static string Track_tour {
            get {
                return ResourceManager.GetString("Track tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neaktivne ture(Ctrl+Tab).
        /// </summary>
        internal static string Unactive_tours_Ctrl_Tab_ {
            get {
                return ResourceManager.GetString("Unactive tours(Ctrl+Tab)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neprocitano.
        /// </summary>
        internal static string Unread {
            get {
                return ResourceManager.GetString("Unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload button.
        /// </summary>
        internal static string Upload_button {
            get {
                return ResourceManager.GetString("Upload button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista vaucera:.
        /// </summary>
        internal static string Voucher_list_ {
            get {
                return ResourceManager.GetString("Voucher list:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vauceri.
        /// </summary>
        internal static string Vouchers {
            get {
                return ResourceManager.GetString("Vouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vauceri(F6).
        /// </summary>
        internal static string Vouchers_F6_ {
            get {
                return ResourceManager.GetString("Vouchers(F6)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imate novu poruku!.
        /// </summary>
        internal static string You_have_new_message_ {
            get {
                return ResourceManager.GetString("You have new message!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vas zahtjev za turu je.
        /// </summary>
        internal static string Your_tour_request_is {
            get {
                return ResourceManager.GetString("Your tour request is", resourceCulture);
            }
        }
    }
}
